title: Ontario Cryptography Day

url: https://ontario-crypto-day.github.io/
repository: ontario-crypto-day/ontario-crypto-day.github.io

theme: minimal-mistakes-jekyll
# documentation: https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/

atom_feed:
  hide: true
